### ISSUE TITLE
Ignoring is broken

### ISSUE THREAD

**Issue by Shimanogov** [Tviskaron/crafting#2]
Suppose that we have a following project structure:

- code
    - c-swm
    - traing.py
    - train.yaml
 
Where train.yaml is a crafting config with the following code parameter:
```
code:
  folder: "."
  volumes:
    - "c-swm"
```
Then running it will result in such an error
```
ValueError: Folder c-swm is too big (>...MB).
Consider adding it to volumes or ignore it in code settings. 
E.g. volumes: ['c-swm'] or ignore: ['c-swm']
```
Adding ignore: ['c-swm'] will not help to solve it also. It seems that ignoring parts of the code folder is broken for now.

**Comment by Tviskaron** [comment]
@Shimanogov thanks, fixed in https://github.com/Tviskaron/crafting/commit/162abacc659feb7c421beada0a4e59f16851aa47
